# Generated by Django 5.2.8 on 2025-11-21 20:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('movimientos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_CRITICO', 'Stock Crítico'), ('STOCK_AGOTADO', 'Stock Agotado'), ('PROXIMO_VENCIMIENTO', 'Próximo a Vencer'), ('PRODUCTO_VENCIDO', 'Producto Vencido'), ('STOCK_EXCESO', 'Exceso de Stock'), ('PRECIO_CAMBIO', 'Cambio de Precio'), ('PEDIDO_PENDIENTE', 'Pedido Pendiente'), ('INVENTARIO_BAJO', 'Inventario Bajo'), ('SIN_MOVIMIENTOS', 'Sin Movimientos Recientes')], max_length=50)),
                ('nivel', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LEIDA', 'Leída'), ('ATENDIDA', 'Atendida'), ('DESCARTADA', 'Descartada')], default='PENDIENTE', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('auto_generada', models.BooleanField(default=False)),
                ('repetible', models.BooleanField(default=True)),
                ('enviar_correo', models.BooleanField(default=False)),
                ('correo_enviado', models.BooleanField(default=False)),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL)),
                ('leida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_leidas', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='movimientos.movimiento')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='Productos.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('STOCK_CRITICO', 'Stock Crítico'), ('STOCK_AGOTADO', 'Stock Agotado'), ('PROXIMO_VENCIMIENTO', 'Próximo a Vencer'), ('PRODUCTO_VENCIDO', 'Producto Vencido'), ('STOCK_EXCESO', 'Exceso de Stock'), ('PRECIO_CAMBIO', 'Cambio de Precio'), ('PEDIDO_PENDIENTE', 'Pedido Pendiente'), ('INVENTARIO_BAJO', 'Inventario Bajo'), ('SIN_MOVIMIENTOS', 'Sin Movimientos Recientes')], max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('auto_generar', models.BooleanField(default=True)),
                ('nivel_predeterminado', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('enviar_correo', models.BooleanField(default=False)),
                ('correo_destinatarios', models.TextField(blank=True, help_text='Emails separados por coma')),
                ('dias_aviso_vencimiento', models.PositiveIntegerField(default=30, help_text='Días de anticipación para alertas de vencimiento', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('porcentaje_stock_critico', models.DecimalField(decimal_places=2, default=20.0, help_text='Porcentaje sobre stock mínimo para considerar crítico', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('intervalo_revision_horas', models.PositiveIntegerField(default=24, help_text='Horas entre revisiones automáticas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Alerta',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
        migrations.CreateModel(
            name='HistorialAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Alertas.alerta')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Alerta',
                'verbose_name_plural': 'Historial de Alertas',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo'], name='Alertas_ale_tipo_dd4011_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['nivel'], name='Alertas_ale_nivel_cd7d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado'], name='Alertas_ale_estado_236ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['activa'], name='Alertas_ale_activa_07172e_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['fecha_creacion'], name='Alertas_ale_fecha_c_afcf03_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['producto', 'tipo', 'activa'], name='Alertas_ale_product_06e524_idx'),
        ),
    ]
