# Generated by Django 5.2.8 on 2025-11-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionalerta',
            name='repetible',
            field=models.BooleanField(default=True, help_text='Indica si pueden generarse múltiples alertas del mismo tipo para un producto'),
        ),
    ]
