# Generated by Django 5.2.8 on 2025-11-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alertas', '0002_configuracionalerta_repetible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=True),
        ),
    ]
