# Generated by Django 5.2.8 on 2025-11-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alertas', '0003_alter_alerta_datos_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='datos_adicionales',
            field=models.JSONField(default=dict, blank=True, null=True),
        ),
    ]
