# Generated by Django 5.2.8 on 2025-11-21 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('SEMILLA', 'Semilla'), ('ABONO', 'Abono'), ('HERBICIDA', 'Herbicida'), ('HERRAMIENTA', 'Herramienta'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, help_text='Stock actual en almacén', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Stock mínimo antes de generar alerta', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_maximo', models.DecimalField(decimal_places=3, default=0, help_text='Capacidad máxima de almacenamiento', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('G', 'Gramos'), ('L', 'Litros'), ('ML', 'Mililitros'), ('UNIDAD', 'Unidades'), ('CAJA', 'Cajas'), ('BOLSA', 'Bolsas')], max_length=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('proveedor_principal', models.CharField(blank=True, help_text='Nombre del proveedor principal', max_length=200)),
                ('ubicacion_almacen', models.CharField(blank=True, help_text='Ubicación en el almacén', max_length=100)),
                ('lote', models.CharField(blank=True, help_text='Número de lote', max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('DESCONTINUADO', 'Descontinuado')], default='DISPONIBLE', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Productos.categoriaproducto')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_compra_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='Productos.producto')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='Productos_p_codigo_9a1185_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='Productos_p_nombre_3c70d2_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='Productos_p_categor_319795_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='Productos_p_estado_aad184_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['fecha_vencimiento'], name='Productos_p_fecha_v_f2b8a2_idx'),
        ),
    ]
